### ISSUE TITLE
Convert the manual to markdown

### ISSUE THREAD

**Issue by aubertc** [poonamveeral/GeneralRepo#2]
I believe [this file](https://github.com/poonamveeral/GeneralRepo/blob/master/install/DocManv5.docx) should really be a markdown file.
As I wrote to Minh,

> I would suggest that you:
> 
> 1. Convert it to markdown using pandoc (so, something like "pandoc DocManv5.docx -o manual.md" should do it),
> 2. Save all the images and figures in a folder,
> 3. Link correctly the images from the markdown source,
> 4. Compile the document into a docx, and see if you are pleased with the result (if not, edit the markdown further),
> 5. Add the markdown source and the figures to the git repo, and invite me.
> 
> That way, we can share the document and I can suggest corrections (or even help you with the formatting) more easily.

I can help you getting started if you want.

**Comment by mtnguye** [comment]
Converted manual to markdown. A few formatting nitpicks that bother me but content is there and readable.
