### ISSUE TITLE
Formatting nitpicks in the manual

### ISSUE THREAD

**Issue by aubertc** [poonamveeral/GeneralRepo#3]
> Converted manual to markdown. A few formatting nitpicks that bother me but content is there and readable.

_Originally posted by @mtnguye in https://github.com/poonamveeral/GeneralRepo/issues/2#issuecomment-602825161_

I'm curious to see what those are.
I have a couple of comments:

- You should give somewhere the command you used to compile the manual. Something like `pandoc manual.md --pdf-engine=xelatex -o manual.pdf`?

- Why are the titles ALL CAPS?

- Using `[STEP 2:]{.underline}` is ok, but it would be better to use a numbered list, or (sub)sections. 

- `<center>…</center>` should be removed.

- When a command span over multiple lines, you should add `\`, cf. <https://superuser.com/a/508508>

- You could add links to the software presented, like <https://github.com/dawbarton/pdf2svg>.

**Comment by mtnguye** [comment]
Bullet 1- Added a comment at the top of manual.md about compiling manual.md. Used same commands as example.md, and lectures_notes.md from CSCI_3410 Makefile

Bullet 2- Removed the all capped titles. The template I used to create the docx manual had all the titles caps. I thought it helped break up the document and made it more readable.  

Bullet 3- Changed Step 1/2 to ## Step 1/2

Bullet 4- Removed center

Bullet 5- Added \ to each line in block code

Bullet 6- Added links to all software requirements. Some links are directed to the download page, some are directed to the main/informational page.

**Comment by aubertc** [comment]
Thanks!

I've just pushed a couple of small changes myself.

As for 2. if you really want the title to be all caps, use CSS (something like `font-variant: small-caps;`), but that's not supposed to be _spelled_ all caps.
